services:
  discord_bot:
    image: ghcr.io/hikariapp/hikari/stable:latest
    container_name: hikari-dpy
    ports:
      - "${WEB_PORT:-9000}:${WEB_PORT:-9000}"
    env_file:
      - .env
    restart: on-failure  # Setting it to 'always' or 'unless-stopped' would broke the shutdown functionality that the bot already have on its own
    init: true  # This is required for enabling proper signal handling

